Repository Platzi-Master-C8/gethired-commons, pull requests merged in 2021-12, with the labels that each got.

#5 fix: update theme provider and add button example
  .gitignore
  .storybook/preview-head.html
  .storybook/preview.js
  package.json
  packages/components/src/ButtonExample/ButtonExample.js
  packages/components/src/ButtonExample/ButtonExample.stories.js
  packages/components/src/index.d.ts
  packages/components/src/index.js
  packages/theme/src/theme/theme.d.ts
  packages/theme/src/theme/theme.js
  yarn.lock
Labels: bug, feature

#10 Hotfixf-9 ThemeProvider doesn't used Default Theme
  packages/theme/package.json
  packages/theme/src/ThemeProvider/ThemeProvider.js
  packages/theme/src/ThemeProvider/Themeprovider.d.ts
  packages/theme/src/colors/theme.d.ts
  packages/theme/src/theme/theme.d.ts
Labels: bug, theme

#12 Feature 11 - Create component header
  packages/components/package.json
  packages/components/src/Header/Header.d.ts
  packages/components/src/Header/Header.js
  packages/components/src/Header/Header.spec.js
  packages/components/src/Header/Header.stories.js
  packages/components/src/Header/Header.styles.js
  packages/components/src/Header/index.d.ts
  packages/components/src/Header/index.js
  packages/components/src/index.d.ts
  packages/components/src/index.js
  packages/icons/package.json
  packages/icons/readme.md
  packages/theme/src/theme/theme.js
Labels: feature, component, storybook

#14 Feature 13 - Add Link label into Header component
  .github/workflows/deploy.yml
  .gitignore
  package.json
  packages/components/src/Header/Header.js
Labels: feature
